version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "secret"
      POSTGRES_USER: "postgre"
      POSTGRES_PASSWORD: '1234'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./server/src:/server/src