version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "$DB_NAME"
      POSTGRES_USER: "$DB_USER"
      POSTGRES_PASSWORD: '$DB_PASSWORD'
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    ports:
      - "${HOST}:$DB_PORT:$DB_PORT"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '${HOST}:$SERVER_PORT:$SERVER_PORT'
    depends_on:
      - postgres
    command: sh -c "wait && npx sequelize-cli db:migrate && npm run start:dev"
    volumes:
      - .:/usr/src/server
volumes:
  db_data: